### PR TITLE
Initial setup

### PR DESCRIPTION
**Pull request by lestoni**
- All features present.
- documentation -> anwani-api.herokuapp.com/documentation

### CODE REVIEW

**Comment by lestoni** [comment]
anwani

**Comment by maxosba** [comment]
Is this published because the documentation link does not work. I get
There is no app configured at that hostname.
Perhaps the app owner has renamed it, or you mistyped the URL.

Regards
Amadou Daffe

**Comment by lestoni** [comment]
@bathie007 can you merge this for me, i dont have write access to the master repo

**Comment by bathie007** [comment]
done @lestoni

**Pull request merged**
